baseURL: "https://ezqzy.xyz/"
languageCode: en-us
title: ezqzy
theme: hugo-PaperMod

params:
  homeInfoParams:
    Title: "Hi!"
    Content: Keyboard, Swift developer and IT enthusiast from a small island in Croatia. Links (icons) below lead to my various social media accounts, you can find my contact info, Youtube channel, Twitter and Bitcoin wallet! My Spotify playlist is also linked if you need something to listen to while programming.
  socialIcons:
    - name: spotify
      url: "https://open.spotify.com/playlist/5xyqP7SSJieDov6f9bkfpw?si=4a82198b02b74385"
    - name: twitter
      url: "https://twitter.com/@ezqzy"
    - name: github
      url: "https://github.com/ezqzy"
    - name: "youtube"
      url: "https://youtube.com/channel/UC7GtlU-aYtDAbpJHh4oaZeA"
    - name: "email"
      mailto: narcisstefanovski@ezqzy.xyz
    - name: "bitcoin"
      url: "https://www.blockchain.com/btc/address/bc1q4d6hpj33ypzq3x0anz3k8xuksa26mwc37v3m49"
  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30

outputs:
    home:
        - HTML
        - RSS
        - JSON
